import test from 'node:test';import assert from 'node:assert/strict';import {BoundaryLab} from '../src/core.js';
const create=x=>x.create({title:'Deploy service',operation:'Simulate deployment'});
test('approval updates exactly its waiting task and emits audit events',()=>{const x=new BoundaryLab();const a=create(x),b=create(x);const r=x.decide(a.id,{decision:'approve',actor:'tester'});assert.equal(r.code,200);assert.equal(r.task.status,'simulated_completed');assert.equal(x.tasks.get(b.id).status,'awaiting_human');assert.deepEqual(x.events.filter(e=>e.taskId===a.id).map(e=>e.type),['boundary.created','boundary.resolved','simulation.continued']);});
test('rejection stops exact task',()=>{const x=new BoundaryLab(),a=create(x);assert.equal(x.decide(a.id,{decision:'reject',actor:'tester'}).task.status,'rejected');});
test('duplicate resolution fails closed without extra events',()=>{const x=new BoundaryLab(),a=create(x);x.decide(a.id,{decision:'approve',actor:'tester'});const before=x.events.length;assert.equal(x.decide(a.id,{decision:'approve',actor:'tester'}).code,409);assert.equal(x.events.length,before);});
test('invalid decision does not mutate state',()=>{const x=new BoundaryLab(),a=create(x);assert.equal(x.decide(a.id,{decision:'force',actor:'tester'}).code,400);assert.equal(x.tasks.get(a.id).status,'awaiting_human');assert.equal(x.decide('unknown',{decision:'approve',actor:'tester'}).code,404);});

test('interleaved decisions preserve identity and event order',()=>{const x=new BoundaryLab();const a=create(x),b=create(x),c=create(x);x.decide(b.id,{decision:'reject',actor:'reviewer-b'});x.decide(a.id,{decision:'approve',actor:'reviewer-a'});assert.equal(x.tasks.get(c.id).status,'awaiting_human');assert.equal(x.events.length,7);assert.deepEqual(x.events.map(e=>e.sequence),[1,2,3,4,5,6,7]);assert.equal(x.events.filter(e=>e.taskId===b.id&&e.type==='simulation.stopped').length,1);assert.equal(x.events.filter(e=>e.taskId===a.id&&e.type==='simulation.continued').length,1);});
test('invalid actor and malformed parameters never resolve waiting work',()=>{const x=new BoundaryLab(),a=create(x);for(const input of [{decision:'approve',actor:''},{decision:'approve',actor:1},{decision:'approve',actor:'x'},{decision:'approve',actor:'valid',reason:1},{decision:'approve',actor:'valid',reason:'x'.repeat(501)}]){assert.equal(x.decide(a.id,input).code,400);assert.equal(x.tasks.get(a.id).status,'awaiting_human');}assert.equal(x.events.length,1);});
test('create validation rejects invalid operations without altering registry',()=>{const x=new BoundaryLab();for(const input of [{title:'',operation:'valid operation'},{title:'Valid title',operation:''},{title:3,operation:'valid operation'},{title:'Valid title',operation:'x'.repeat(501)}]){assert.throws(()=>x.create(input));}assert.equal(x.tasks.size,0);assert.equal(x.events.length,0);});
test('snapshot is isolated from caller mutation',()=>{const x=new BoundaryLab(),a=create(x);const s=x.snapshot();s.tasks[0].status='tampered';s.events[0].type='tampered';assert.equal(x.tasks.get(a.id).status,'awaiting_human');assert.equal(x.events[0].type,'boundary.created');});
